// <auto-generated />
using System;
using IndividualsDirectory.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IndividualsDirectory.Infrastructure.Migrations
{
    [DbContext(typeof(IndividualsDbContext))]
    partial class IndividualsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IndividualsDirectory.Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Cities", t =>
                        {
                            t.HasCheckConstraint("CHK_CityName", "Name COLLATE Latin1_General_BIN NOT LIKE '%[ა-ჰ]%' OR Name COLLATE Georgian_Modern_Sort_BIN NOT LIKE '%[A-Za-z]%'");
                        });
                });

            modelBuilder.Entity("IndividualsDirectory.Domain.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Persons", t =>
                        {
                            t.HasCheckConstraint("CHK_BirthDate", "DATEDIFF(year, BirthDate, GETDATE()) >= 18");

                            t.HasCheckConstraint("CHK_FirstName", "FirstName COLLATE Latin1_General_BIN NOT LIKE '%[ა-ჰ]%' OR FirstName COLLATE Georgian_Modern_Sort_BIN NOT LIKE '%[A-Za-z]%'");

                            t.HasCheckConstraint("CHK_LastName", "LastName COLLATE Latin1_General_BIN NOT LIKE '%[ა-ჰ]%' OR LastName COLLATE Georgian_Modern_Sort_BIN NOT LIKE '%[A-Za-z]%'");

                            t.HasCheckConstraint("CHK_PersonalNumber", "LEN(PersonalNumber) = 11 AND PersonalNumber NOT LIKE '%[^0-9]%'");
                        });
                });

            modelBuilder.Entity("IndividualsDirectory.Domain.PhoneNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumberType")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PhoneNumbers", t =>
                        {
                            t.HasCheckConstraint("CHK_PhoneNumber", "LEN(Number) BETWEEN 4 AND 50");
                        });
                });

            modelBuilder.Entity("IndividualsDirectory.Domain.RelatedIndividual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("RelatedPersonId")
                        .HasColumnType("int");

                    b.Property<int>("Relationship")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("RelatedPersonId");

                    b.ToTable("RelatedIndividuals");
                });

            modelBuilder.Entity("IndividualsDirectory.Domain.Person", b =>
                {
                    b.HasOne("IndividualsDirectory.Domain.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("IndividualsDirectory.Domain.PhoneNumber", b =>
                {
                    b.HasOne("IndividualsDirectory.Domain.Person", "Person")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("IndividualsDirectory.Domain.RelatedIndividual", b =>
                {
                    b.HasOne("IndividualsDirectory.Domain.Person", "Person")
                        .WithMany("RelatedIndividuals")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IndividualsDirectory.Domain.Person", "RelatedPerson")
                        .WithMany()
                        .HasForeignKey("RelatedPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("RelatedPerson");
                });

            modelBuilder.Entity("IndividualsDirectory.Domain.Person", b =>
                {
                    b.Navigation("PhoneNumbers");

                    b.Navigation("RelatedIndividuals");
                });
#pragma warning restore 612, 618
        }
    }
}
